# Generated by Django 3.1.1 on 2021-03-19 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20210316_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=django.utils.timezone.now, max_digits=2),
            preserve_default=False,
        ),
    ]
